sonar.projectKey=sunnatillatotsamiy_sqpt_demo_00015751
sonar.organization=sunnatillatotsamiy
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml 
sonar.qualitygate.wait=true
